[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=86400, stale-while-revalidate=604800"

[[headers]]
  for = "/images/thumbs/*"
  [headers.values]
    Cache-Control = "public, max-age=604800, stale-while-revalidate=2592000"

[[headers]]
  for = "/images/thumbs-mobile/*"
  [headers.values]
    Cache-Control = "public, max-age=604800, stale-while-revalidate=2592000"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
